# Generated by Django 4.1.3 on 2022-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('date_of_brith', models.DateField()),
                ('Post', models.CharField(choices=[('PM', 'Project Manager'), ('WD', 'Web Developer'), ('SE', 'Sotware Engineer'), ('AI', 'Aritificial Intellgence'), ('A', 'Asistant')], default='A', max_length=50)),
                ('joined_date', models.DateField()),
            ],
        ),
    ]
